import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage: "url('/public/environment2.png')",
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundAttachment: 'fixed', // optional: parallax effect
          backgroundRepeat: 'no-repeat',
          minHeight: '100vh',
          margin: 0,
        }}>
        {children}
        <script 
        dangerouslySetInnerHTML={{
          __html:`
           (function(){
            const theme =  localStorage.getItem('theme')||
                          (window.matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');
              if(theme ==='dark'){
                document.documentElement.classList.add('dark');
              }
           })();
           `,
        }}
        />
      </body>
    </html>
  );
}
